In [2]:
import numpy as np  
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
np.array([1.1,2,3,4])

array([1.1, 2. , 3. , 4. ])

In [4]:
np.array(['1',2,3,4,5])

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [5]:
np.array(['test',1,2,3,4])

array(['test', '1', '2', '3', '4'], dtype='<U4')

In [6]:
np.array([1,2,3,4,5],dtype='float64')

array([1., 2., 3., 4., 5.])

In [10]:
np.array([[1,2,3],[4,5,6],[7,8,9]],dtype='float32')

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [17]:
np.array([range(i, i + 4) for i in [1, 2, 4]])

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [4, 5, 6, 7]])

In [19]:
np.ones((3,5), int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [22]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.full((3,2), 2.1)

array([[2.1, 2.1],
       [2.1, 2.1],
       [2.1, 2.1]])

In [26]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [27]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [28]:
np.arange(1,21,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [29]:
np.random.random((5,5))

array([[0.05149467, 0.5163842 , 0.52647254, 0.69317107, 0.28220248],
       [0.78287599, 0.11349624, 0.05183202, 0.34198125, 0.18317425],
       [0.82945815, 0.35489875, 0.00564659, 0.72752158, 0.25915743],
       [0.90950275, 0.24902233, 0.97900032, 0.9686515 , 0.85619859],
       [0.64844299, 0.15019341, 0.67003976, 0.83655608, 0.73682896]])

In [32]:
A=np.random.normal(0,1,(3,5))
A

array([[-0.45687527, -0.53118306,  0.68654469, -0.54115892,  0.61509555],
       [ 1.67856531, -1.09376228,  0.92816138,  1.35032675, -0.880352  ],
       [-0.39831704,  0.85924465,  0.8482853 ,  1.32286457, -0.11643452]])

In [37]:
np.random.randint(0,10,(2,3))

array([[9, 8, 8],
       [5, 9, 2]])

In [38]:
np.empty(3)

array([1.36406229e-311, 0.00000000e+000, 1.33360289e+241])

In [39]:
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [41]:
np.ones((3,3), dtype=np.bool_)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [45]:
np.zeros((3,3), dtype=np.float64)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])